[package]
name = "github-repo-dl"
version = "0.1.0"
authors = ["Luke Chen Shui <chenshuiluke@gmail.com>"]

[dependencies]
github-rs = "0.5"
terminal_size = {git = "https://github.com/eminence/terminal-size"}
serde_json = "1.0"
hyper = "0.11"
